extends: substitution
message: "Use '%s' instead of '%s'."
level: error
ignorecase: false
swap:
  Github: GitHub
  Git Hub: GitHub
  Spore language: Spore
  spore language: Spore
  pullrequest: pull request
  Pullrequest: Pull request
  spore proposal: SEP
  Spore proposal: SEP
  spore enhancement proposal: SEP
  Spore enhancement proposal: SEP
